Dev
ujjawal-1999/Resource-Hub-NITS pull request #12
Opened 2021-09-04 19:38 UTC by Sayahnneeta

2021-09-05 05:40 UTC, aditya2712 commented
Remove the logo for now

2021-09-05 05:43 UTC, aditya2712 requested changes
Remove the logo for now, and leave that space blank. Later we will add the final logo.

2021-09-05 16:06 UTC, aditya2712 approved these changes

2021-09-05 16:53 UTC, Sayahnneeta commented
merge conflicts in signup/login page in external links resolved

2021-09-06 08:14 UTC, aditya2712 approved these changes

2021-09-06 08:15 UTC, merged